/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/public/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/login-google-oauth2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login_google_oauth2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_home_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/note/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_note_save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/note/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_note_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat-status/{inner_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mgr/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_all_notes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mgr/note/{inner_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_note_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/note/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_shared_note_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mgr/note/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_note_by_slug"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/note/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_notes_by_similarity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/qiniu/uptoken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_qiniu_upload_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
type JsonRequestBody<T> = {
    content: {
        "application/json": T;
    };
};
type JsonResponse<T> = {
    headers: {
        [name: string]: unknown;
    };
    content: {
        "application/json": T;
    };
};
type EmptyResponse = {
    headers: {
        [name: string]: unknown;
    };
};
export interface components {
    schemas: {
        /** ChatNoteInput */
        ChatNoteInput: {
            /** Slug */
            slug: string;
            /** Userprompt */
            userPrompt: string;
        };
        /** ChatStatusDto */
        ChatStatusDto: {
            /** Status */
            status: number;
            /**
             * Total Tokens
             * @default null
             */
            total_tokens: number | null;
            /**
             * Message
             * @default null
             */
            message: string | null;
        };
        /**
         * GoogleOAuth2LoginRequest
         * @description Google OAuth2登录请求
         */
        GoogleOAuth2LoginRequest: {
            /** Code */
            code: string;
            /** Redirecturi */
            redirectUri: string;
        };
        /** QiniuUploadTokenResponse */
        QiniuUploadTokenResponse: {
            /** Uptoken */
            uptoken: string;
        };
        /** ListMgrNoteDto */
        ListMgrNoteDto: {
            /** Slug */
            slug: string;
            /** Innerslug */
            innerSlug: string | null;
            /** Contentmd */
            contentMd: string;
            /** Title */
            title: string;
            /** Contenthtml */
            contentHtml: string | null;
            /** Isshared */
            isShared: number;
            /**
             * Createtime
             * Format: date-time
             */
            createTime: string;
            /**
             * Updatetime
             * Format: date-time
             */
            updateTime: string;
            /** Createip */
            createIp: string;
            /** Updateip */
            updateIp: string;
            /** Uv */
            uv: number;
            /**
             * Embedding
             * @default null
             */
            embedding: number[] | null;
        };
        /** ListSearchNoteDto */
        ListSearchNoteDto: {
            /** Slug */
            slug: string;
            /** Innerslug */
            innerSlug: string | null;
            /** Title */
            title: string;
            /** Contentmd */
            contentMd: string;
            /** Similarity */
            similarity: number;
            /**
             * Createtime
             * Format: date-time
             */
            createTime: string;
            /**
             * Updatetime
             * Format: date-time
             */
            updateTime: string;
        };
        /**
         * LoginRequest
         * @description 登录请求
         */
        LoginRequest: {
            /** Username */
            userName: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description 登录响应
         */
        LoginResponse: {
            /** Token */
            token: string;
        };
        /** SaveNoteInput */
        SaveNoteInput: {
            /** Slug */
            slug: string;
            /** Contentmd */
            contentMd: string;
            /** Isshared */
            isShared: number;
        };
        /** SharedNoteDto */
        SharedNoteDto: {
            /** Slug */
            slug: string;
            /** Contentmd */
            contentMd: string;
            /** Isshared */
            isShared: number;
            /**
             * Createtime
             * Format: date-time
             */
            createTime: string;
            /**
             * Updatetime
             * Format: date-time
             */
            updateTime: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: JsonRequestBody<components["schemas"]["LoginRequest"]>;
        responses: {
            200: JsonResponse<components["schemas"]["LoginResponse"]>;
        };
    };
    login_google_oauth2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: JsonRequestBody<components["schemas"]["GoogleOAuth2LoginRequest"]>;
        responses: {
            200: JsonResponse<components["schemas"]["LoginResponse"]>;
        };
    };
    get_home_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: JsonResponse<unknown>;
        };
    };
    post_api_note_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: JsonRequestBody<components["schemas"]["SaveNoteInput"]>;
        responses: {
            200: EmptyResponse;
        };
    };
    post_api_note_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: JsonRequestBody<components["schemas"]["ChatNoteInput"]>;
        responses: {
            200: EmptyResponse;
        };
    };
    get_chat_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inner_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: JsonResponse<components["schemas"]["ChatStatusDto"]>;
        };
    };
    get_all_notes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: JsonResponse<components["schemas"]["ListMgrNoteDto"][]>;
        };
    };
    get_note_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inner_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: JsonResponse<components["schemas"]["ListMgrNoteDto"]>;
        };
    };
    get_shared_note_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: JsonResponse<components["schemas"]["SharedNoteDto"]>;
        };
    };
    delete_note_by_slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: EmptyResponse;
        };
    };
    search_notes_by_similarity: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: JsonResponse<components["schemas"]["ListSearchNoteDto"][]>;
        };
    };
    get_qiniu_upload_token: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: JsonResponse<components["schemas"]["QiniuUploadTokenResponse"]>;
        };
    };
}
